[package]
name = "function_like_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.57", features = ["full", "fold"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["nightly"] }